name: ESLint

on:
  push:
    branches: ["master"]
    paths: ["mapkom_client/**"]
  pull_request:
    branches: ["master"]
    paths: ["mapkom_client/**"]

jobs:
  eslint:
    name: Run eslint analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
          cache-dependency-path: mapkom_client/yarn.lock

      - name: Install dependencies
        run: yarn install
        working-directory: mapkom_client

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: yarn eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        working-directory: mapkom_client
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: mapkom_client/eslint-results.sarif
          wait-for-processing: true
